package com.poly.common;

public enum PageType {
    USER_MANAGEMENT_PAGE, 
    REPORTS_MANAGEMENT_PAGE, 
    VIDEO_MANAGEMENT_PAGE,
    
    SITE_HOME_PAGE, 
    SITE_LOGIN_PAGE, 
    SITE_REGISTRATION_PAGE, 
    SITE_CHANGEPASS_PAGE,
    SITE_EDIT_PROFILE_PAGE, 
    SITE_FORGOT_PASS_PAGE, 
    SITE_VIDEO_DETAIL_PAGE,
    SITE_FAVORITE_PAGE, 
    SITE_SHARE_PAGE
}
